# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end


target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner
  capacitor_pods
  pod 'Intercom'
end

target 'PluginTests' do
  use_frameworks!

  capacitor_pods
  pod 'Intercom', '~> 10.0'
end
